### PR TITLE
Provide custom frame filtering options

### LINKED ISSUE #25: Provide custom frame filtering option
I'm using color-backtrace along with rayon.

The trouble is that rayon produces absurdly long stack traces. I'm looking at one with 150 frames right now.

These long stack traces push my interesting stack traces way way up my scroll buffer.

I'd like to filter out the rayon stack frames. Its probably too much to task for color-backtrace to do it for me, but it'd be nice if I had the option to provide custom filtering logic.

### PR DESCRIPTION
**Pull request by yaahc**
closes #25

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -135,10 +135,18 @@ pub fn install_with_settings(printer: BacktracePrinter) {
...
-    lineno: Option<u32>,
-    filename: Option<PathBuf>,
+pub type FilterCallback = dyn Fn(Vec<&Frame>) -> Vec<&Frame> + Send + Sync + 'static;
+
+// TODO worried about this as a forward compatibility hazard, we might want to add a hidden zero
+// sized field that prevents the constructor from getting exported, otherwise adding a field here
+// would be a breaking change I think.
+//
+// At the very least we should verify that this cannot be constructed in foreign crates.
+pub struct Frame {
```
Comment (yaahc) [inline src/lib.rs:140]: worried about this as a forward compatibility hazard, we might want to add a hidden zero
sized field that prevents the constructor from getting exported, otherwise adding a field here
would be a breaking change I think.

At the very least we should verify that this cannot be constructed in foreign crates.

File: src/lib.rs [hunk 2]
```diff
@@ -485,25 +538,25 @@ impl BacktracePrinter {
...
-            .unwrap_or(0);
+        // Turn them into `Frame` objects and print them.
+        let num_frames = frames.len();
 
-        // Try to find where language init frames start ...
-        let bottom_cutoff = frames
-            .iter()
-            .position(Frame::is_runtime_init_code)
-            .unwrap_or_else(|| frames.len());
+        let mut frames = frames.iter().collect();
```
Comment (yaahc) [inline src/lib.rs:548]: Would it be better to use `Vec::retain` here and pass `&mut Vec<Frames>` as the argument to filters? I'm worried that this will cause a lot of unnecessary allocations.

**Comment by yaahc** [comment]
build failing because stable isn't available, nice :)

File: src/lib.rs (hunk 1 above)
Comment (athre0z) [reply src/lib.rs:140]: Yes -- I'll definitely do that!

File: src/lib.rs (hunk 2 above)
Comment (athre0z) [reply src/lib.rs:548]: Well, would it be better. Performance-wise? Probably. Interface-wise. Hmm.

Comment (athre0z) [reply src/lib.rs:548]: Well, it would even be shorter than calling `.into_iter()` and `.collect()`. 

```rust
fn filter(frames: &mut Vec<Frame>) {
    frames.retain(|x| matches!(&x.name, Some(n) if n.starts_with("oof")));
}
```

Actually, this is elegant AF. Let's go for it. Excellent idea!

**Comment by athre0z** [comment]
Thanks for the great PR. I really didn't have to change a lot!

For the spacers, I tried different things and thought that it would be cool to go with the zig-zag look that GitHub does when it truncates an enormously long issue:

Zg9qoS9mLXv9stpq

That's what it looks like with my current glyph selection in iTerm:

TBh1NUeHLFthbF2Z

I think it's okay, but I'll look into other glyphs.

Alternatively, the with the glyph I originally proposed:

q5THIHQY4kLTJ792

**Comment by yaahc** [comment]
I'm not sure if it just takes some getting used but rn I think I prefer the second option

**Comment by athre0z** [comment]
Yeah, I'd go with the second one of those two as well. There's a quite significant lack of unicode characters for displaying medium height wavy/zigzag horizontal lines. I found two more options:

## `〰`

iTerm
Screen Shot 2020-05-02 at 15 14 56

Gnome Term
Screen Shot 2020-05-02 at 15 36 12

## `ᨓ`

Screen Shot 2020-05-02 at 15 26 26

Screen Shot 2020-05-02 at 15 31 56

None of them is really just perfect.

**Comment by yaahc** [comment]
Sounds good, I agree with you that the second option here also looks pretty good but I don't have a strong preference.

**Comment by athre0z** [comment]
Alright, I just went with the somewhat more conservative `⋮` for now. I'll test out some more options and maybe make it configurable & launch a Twitter poll for the default later, but don't want to block this any longer. Additionally, I migrated the CI to GH Actions, which seems to be working fine.

Did I forget anything? From my side of things, this should be ready to merge.

**Comment by yaahc** [comment]
Nope, I think this ones good for me

**Comment by athre0z** [comment]
I'll do a release tomorrow, after doing some additional testing. I want to make sure that no off-by-ones are introduced -- having the wrong frames hidden would be a really major PITA for everyone trying to debug their app using the lib.
